/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeaturedIndexRouteImport } from './routes/featured.index'
import { Route as FeaturedMscThesisRouteImport } from './routes/featured.msc-thesis'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedIndexRoute = FeaturedIndexRouteImport.update({
  id: '/featured/',
  path: '/featured/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedMscThesisRoute = FeaturedMscThesisRouteImport.update({
  id: '/featured/msc-thesis',
  path: '/featured/msc-thesis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/featured/msc-thesis': typeof FeaturedMscThesisRoute
  '/featured/': typeof FeaturedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/featured/msc-thesis': typeof FeaturedMscThesisRoute
  '/featured': typeof FeaturedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/featured/msc-thesis': typeof FeaturedMscThesisRoute
  '/featured/': typeof FeaturedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/projects'
    | '/sitemap.xml'
    | '/featured/msc-thesis'
    | '/featured/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/projects'
    | '/sitemap.xml'
    | '/featured/msc-thesis'
    | '/featured'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/projects'
    | '/sitemap.xml'
    | '/featured/msc-thesis'
    | '/featured/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  FeaturedMscThesisRoute: typeof FeaturedMscThesisRoute
  FeaturedIndexRoute: typeof FeaturedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured/': {
      id: '/featured/'
      path: '/featured'
      fullPath: '/featured/'
      preLoaderRoute: typeof FeaturedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured/msc-thesis': {
      id: '/featured/msc-thesis'
      path: '/featured/msc-thesis'
      fullPath: '/featured/msc-thesis'
      preLoaderRoute: typeof FeaturedMscThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  FeaturedMscThesisRoute: FeaturedMscThesisRoute,
  FeaturedIndexRoute: FeaturedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
